name: Auto add reviewer

on:
  pull_request_target:
    types:
      - opened
      - reopened
    branches:
      - main
      - master

jobs:
  add-reviewer:
    name: Add reviewer
    uses: book000/templates/.github/workflows/reusable-add-reviewer.yml@e87b0732e45ca1ef33e1448ce85ad2eee8c5f648 # master
